This is makeindex, version 2.16 [MiKTeX 22.8].
Scanning style file ./bachelorarbeit_pdf_webapp.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file bachelorarbeit_pdf_webapp.acn....done (70 entries accepted, 0 rejected).
Sorting entries....done (603 comparisons).
Generating output file bachelorarbeit_pdf_webapp.acr....done (21 lines written, 0 warnings).
Output written in bachelorarbeit_pdf_webapp.acr.
Transcript written in bachelorarbeit_pdf_webapp.alg.
